### PR TITLE
Laravel 10

### PR DESCRIPTION
**Pull request by inmanturbo**

### CODE REVIEW

**Review by muffycompo — CHANGES_REQUESTED** [review]
@inmanturbo I tested your changes and got some errors regarding php 8.1 and laravel 10. Maybe because it is missing in this line `"php": "^7.4|^8.0|^8.1"`.

Lastly, the orchestra/testbench should include version 8 to support laravel 10. i.e. `"orchestra/testbench": "^6.0|^7.0|^8.0"`

**Comment by inmanturbo** [comment]
@muffycompo Sorry about the oversite! And thank you. I've made the requested changes. Also changed the `phpunit` line to allow `^9.0|^10.0`.

**Comment by muffycompo** [comment]
@davidhsianturi, just a nod :) 

Any chance this PR by @inmanturbo will be reviewed, merged and tagged? Currently holding us back from migrating our project to Laravel 10. Thanks.

**Comment by davidhsianturi** [comment]
@inmanturbo thanks for your PR! the test for Laravel 10 should be included. I'll close this in favor of #90 

@muffycompo sure, the release will be ready later this week.

**Comment by swapnilsarwe** [comment]
@davidhsianturi - any plans about merging this.

your release would help us to get one step closer to make [blade-ui-kit.com](https://github.com/blade-ui-kit/blade-ui-kit.com/pull/104) laravel 10 compatible

**Pull request closed without merging**
